# ci-base
#
# Basic Docker image for CI services
#

FROM ubuntu:12.04
MAINTAINER Kirill Evstigneev <kevstigneev@griddynamics.com>

RUN apt-get -q update \
    && apt-get -qy install net-tools wget openjdk-7-jre-headless

