# ci-base
#
# Basic Docker image for CI services
#

FROM centos:6
MAINTAINER Kirill Evstigneev <kevstigneev@griddynamics.com>

RUN yum -y install tar wget java-1.8.0-openjdk

# Enable EPEL repository (https://fedoraproject.org/wiki/EPEL)
RUN yum -y install epel-release

