# volume
#
# Universal volume container
#
# Build:
# sudo docker build -t cisandbox/volume:{revision} .
# sudo docker tag cisandbox/volume:{revision} cisandbox/volume:latest
#
# Run:
# sudo docker run --name dev-{service}-volume cisandbox/volume
#


FROM tianon/true
MAINTAINER Kirill Evstigneev <kevstigneev@griddynamics.com>

